const { Client } = require("pg")
require("dotenv").config()
const bcrypt = require("bcrypt")

const SQL = `
CREATE TABLE IF NOT EXISTS conta_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS conta_password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES conta_users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT PRIMARY KEY,
  trip_date DATE NOT NULL,
  income NUMERIC NOT NULL DEFAULT 0,
  notes TEXT NULL,
  truck_label TEXT NULL,
  route_label TEXT NULL,
  distance_km NUMERIC NOT NULL DEFAULT 0,
  fuel_consumed NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT PRIMARY KEY,
  exprense_date DATE NOT NULL,
  category TEXT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  notes TEXT NULL,
  truck_label TEXT NULL
);

ALTER TABLE trips
  ADD COLUMN IF NOT EXISTS truck_label TEXT NULL,
  ADD COLUMN IF NOT EXISTS route_label TEXT NULL,
  ADD COLUMN IF NOT EXISTS distance_km NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fuel_consumed NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS truck_label TEXT NULL;

WITH seed(trip_date, income, notes, truck_label, route_label, distance_km, fuel_consumed) AS (
  VALUES
    ('2026-04-01'::date, 120.50::numeric, 'Airport run + short city dropoff'::text, 'Camion A / ML-001'::text, 'Kati - Faladiè'::text, 32::numeric, 25::numeric),
    ('2026-04-05'::date, 280.00::numeric, 'Weekend trips'::text, 'Camion B / ML-002'::text, 'Koulikoro - Moribabougou'::text, 78::numeric, 60::numeric),
    ('2026-04-12'::date, 75.25::numeric,  'Late night ride'::text, 'Camion A / ML-001'::text, 'Faladiè - Kati'::text, 32::numeric, 20::numeric),
    ('2026-04-18'::date, 430.00::numeric, 'Long-distance trip'::text, 'Camion C / ML-003'::text, 'Bamako - Koulikoro'::text, 61::numeric, 80::numeric)
),
max_id AS (
  SELECT COALESCE(MAX(id), 0) AS m FROM trips
),
numbered AS (
  SELECT ROW_NUMBER() OVER () AS rn, trip_date, income, notes, truck_label, route_label, distance_km, fuel_consumed
  FROM seed
)
INSERT INTO trips (id, trip_date, income, notes, truck_label, route_label, distance_km, fuel_consumed)
SELECT (max_id.m + numbered.rn)::bigint, numbered.trip_date, numbered.income, numbered.notes, numbered.truck_label, numbered.route_label, numbered.distance_km, numbered.fuel_consumed
FROM max_id, numbered;

WITH seed(exprense_date, category, amount, notes, truck_label) AS (
  VALUES
    ('2026-04-02'::date, 'Achat carburant'::varchar, 45.20::numeric, 'Gas station'::text, 'Camion A / ML-001'::text),
    ('2026-04-03'::date, 'Vidange'::varchar, 120.00::numeric, 'Oil change'::text, 'Camion B / ML-002'::text),
    ('2026-04-10'::date, 'Péage'::varchar, 18.75::numeric, 'Highway tolls'::text, 'Camion A / ML-001'::text),
    ('2026-04-15'::date, 'Maintenance'::varchar, 12.00::numeric, 'City parking'::text, 'Camion C / ML-003'::text)
),
max_id AS (
  SELECT COALESCE(MAX(id), 0) AS m FROM expenses
),
numbered AS (
  SELECT ROW_NUMBER() OVER () AS rn, exprense_date, category, amount, notes, truck_label
  FROM seed
)
INSERT INTO expenses (id, exprense_date, category, amount, notes, truck_label)
SELECT (max_id.m + numbered.rn)::int, numbered.exprense_date, numbered.category, numbered.amount, numbered.notes, numbered.truck_label
FROM max_id, numbered;
`

async function main() {
  console.log("seeding...")

  const adminUsername = process.env.SEED_ADMIN_USERNAME || "admin"
  const adminPassword = process.env.SEED_ADMIN_PASSWORD || "admin123"
  const adminHash = await bcrypt.hash(adminPassword, 12)

  const client = new Client({
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PWD,
    port: Number(process.env.DB_PORT),
    ssl: { rejectUnauthorized: false },
  })

  await client.connect()

  await client.query(SQL)

  await client.query(
    `INSERT INTO conta_users (username, password_hash, is_admin)
     VALUES ($1, $2, true)
     ON CONFLICT (username) DO NOTHING`,
    [adminUsername, adminHash]
  )
  await client.end()

  console.log("done")
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
